# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_show_books = QtWidgets.QPushButton(self.centralwidget)
        self.btn_show_books.setGeometry(QtCore.QRect(30, 20, 180, 30))
        self.btn_show_books.setObjectName("btn_show_books")
        self.btn_show_genres = QtWidgets.QPushButton(self.centralwidget)
        self.btn_show_genres.setGeometry(QtCore.QRect(230, 20, 180, 30))
        self.btn_show_genres.setObjectName("btn_show_genres")
        self.btn_add_book = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_book.setGeometry(QtCore.QRect(30, 70, 180, 30))
        self.btn_add_book.setObjectName("btn_add_book")
        self.btn_add_genre = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_genre.setGeometry(QtCore.QRect(230, 70, 180, 30))
        self.btn_add_genre.setObjectName("btn_add_genre")
        self.btn_delete_book = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete_book.setGeometry(QtCore.QRect(30, 120, 180, 30))
        self.btn_delete_book.setObjectName("btn_delete_book")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(450, 20, 400, 500))
        self.tableView.setObjectName("tableView")
        self.input_book_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_book_name.setGeometry(QtCore.QRect(30, 200, 180, 30))
        self.input_book_name.setObjectName("input_book_name")
        self.input_book_genre_id = QtWidgets.QLineEdit(self.centralwidget)
        self.input_book_genre_id.setGeometry(QtCore.QRect(30, 240, 180, 30))
        self.input_book_genre_id.setObjectName("input_book_genre_id")
        self.input_book_price = QtWidgets.QLineEdit(self.centralwidget)
        self.input_book_price.setGeometry(QtCore.QRect(30, 280, 180, 30))
        self.input_book_price.setObjectName("input_book_price")
        self.input_book_count = QtWidgets.QLineEdit(self.centralwidget)
        self.input_book_count.setGeometry(QtCore.QRect(30, 320, 180, 30))
        self.input_book_count.setObjectName("input_book_count")
        self.input_genre_id = QtWidgets.QLineEdit(self.centralwidget)
        self.input_genre_id.setGeometry(QtCore.QRect(230, 200, 180, 30))
        self.input_genre_id.setObjectName("input_genre_id")
        self.input_genre_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_genre_name.setGeometry(QtCore.QRect(230, 240, 180, 30))
        self.input_genre_name.setObjectName("input_genre_name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bookshop"))
        self.btn_show_books.setText(_translate("MainWindow", "Показать книги"))
        self.btn_show_genres.setText(_translate("MainWindow", "Показать жанры"))
        self.btn_add_book.setText(_translate("MainWindow", "Добавить книгу"))
        self.btn_add_genre.setText(_translate("MainWindow", "Добавить жанр"))
        self.btn_delete_book.setText(_translate("MainWindow", "Удалить книгу"))
        self.input_book_name.setPlaceholderText(_translate("MainWindow", "Название книги"))
        self.input_book_genre_id.setPlaceholderText(_translate("MainWindow", "ID жанра"))
        self.input_book_price.setPlaceholderText(_translate("MainWindow", "Цена"))
        self.input_book_count.setPlaceholderText(_translate("MainWindow", "Количество"))
        self.input_genre_id.setPlaceholderText(_translate("MainWindow", "ID жанра"))
        self.input_genre_name.setPlaceholderText(_translate("MainWindow", "Название жанра"))
